name: ume_kit_clean_local_data
description: Clean local data tool for UME Kit
version: 2.0.0
homepage: https://github.com/ume-community/ume_kits

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ume_core: ^2.0.1

  path_provider: ^2.0.0
  data_size: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.12

flutter:
  uses-material-design: true
