name: ume_kit_database
description: Database kit for SQLite, hive and SP.
version: 2.0.0
homepage: https://github.com/ume-community/ume_kits

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  data_table_2: ^2.2.1
  flutter:
    sdk: flutter
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2+1
  translator: ^1.0.0
  path: ^1.9.0

  ume_core: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
