name: ume_kit_channel_observer
description: Channel Observer for UME Kit
version: 2.0.1
homepage: https://github.com/ume-community/ume_kits

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ume_core: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  plugin:
    platforms:
      android:
        package: com.lijiaqi.ume_kit_channel_observer
        pluginClass: UmeKitChannelObserverPlugin
      ios:
        pluginClass: UmeKitChannelObserverPlugin

  assets:
    - assets/channel.png
