name: ume_kit_console
description: Show debugPrint kit for ume.
version: 2.0.0
homepage: https://github.com/ume-community/ume_kits

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.0
  share: ^2.0.4
  shared_preferences: ^2.0.6

  ume_core: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65

flutter:
  uses-material-design: true
