name: ume_kit_slow_animation
description: Make the animation slow or fast for UME.
version: 2.0.0
homepage: https://github.com/ume-community/ume_kits

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ume_core: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
