name: ume_kit_monitor
description: Monitor plugin for UME.
version: 2.0.0
homepage: https://github.com/ume-community/ume_kits

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ume_core: ^2.0.1

  cached_network_image:
  dio:
  teledart:
  oktoast:
  path_provider:
  crypto:
  convert:
  url_launcher:
  json_shrink_widget:
