name: ume_kit_memory_detector
description: Memory detector kit for UME.
version: 2.0.1
homepage: https://github.com/ume-community/ume_kits

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ume_core: ^2.0.1

  vm_service: ^14.2.5
  path: ^1.8.0
  sqflite: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.lijiaqi.ume_kit_memory_detector
        pluginClass: UmeKitMemoryDetectorPlugin
      ios:
        pluginClass: UmeKitMemoryDetectorPlugin

  assets:
    - assets/detectc.png
